FORMAT: 1A
HOST: https://localhost/

# Employee Entries

Simple API allowing collection of employee and viewing, editing, and deleting employee data

## Employees [/employees]

### List All Employees [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "nama": "Joko",
                "posisi": "CEO"
            },
            {
                "id": 2,
                "nama": "Joko 2",
                "posisi": "CEO 2"
            }
        ]

### Hire an Employee [POST]

Recruit new employee

+ Request (application/json)

        {
            "nama": "Handoko",
            "posisi": "Janitor"
        }

+ Response 201 (application/json)

    + Headers

            Location: /employees/3

    + Body

            {
                "message": "Employee succesfully entered",
                "status": true,
            }

## Individual Employee [/get-employees/id=1]

### Get Employee by ID [GET]

Get individual employee's data by ID

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "nama": "Joko",
                "posisi": "CEO"
            }
        ]